### ISSUE TITLE
org-roam-sbl-scan-for-broken-links doesn't work with org-roam version 1.2.2

### ISSUE THREAD

**Issue by edmundmiller** [twitchy-ears/org-roam-sbl-show-broken-links#2]
`org-roam-sbl-show-all-broken-links` breaks with

```
org-roam-sbl-scan-for-broken-links: Wrong type argument: stringp, to
```

`org-roam-sbl-show-broken-links` works just fine though.

I don't know if it's related to the new org-roam version or not.

**Comment by twitchy-ears** [comment]
It's because org-roam-sbl-scan-for-broken-links generates the links to check in different ways on if its called with an optional argument for all links.

So if you're just scanning the current entry it calls the (org-roam--extract-links) wrapper and pulls links out live from the current entry.

However org-roam-sbl-show-all-broken-links calls (org-roam-sbl-scan-for-broken-links  t) and it scans the database version, which was broken by the DB schema upgrade as you predicted.

I've put a switch in place so it does the right query based on database version, can you update your copy and check it works for you?

**Comment by edmundmiller** [comment]
Awesome that worked! Thanks for the quick fix again!
